#==============#
# Camera Model #
#==============#

Camera:
# Logitech C270 at 640p
  name: "Logitech C270"
  setup: "monocular"
  model: "perspective"

# Par√°metros calculados, no calibrados:
  cols: 640
  rows: 480

  fx: 451
  fy: 451
  cx: 320
  cy: 240

  k1: 0.0
  k2: 0.0  
  p1: 0.0  
  p2: 0.0
  k3: 0.0

  fps: 30.0

  color_order: "BGR"

#====================#
# Mapping Parameters #
#====================#

Mapping:
